// See https://aka.ms/new-console-template for more information
Console.WriteLine("Typy zmiennych\nOperatory arytmetyczne i logiczne");
Console.WriteLine("Typy wartościowe i referencyjne");
Console.WriteLine("Pętle");
Console.WriteLine("Warunki");
Console.WriteLine("Tablice");
Console.WriteLine("Listy");
Console.WriteLine("Słowniki");
Console.WriteLine("Inne kolekcje jak stos, kolejka");
Console.WriteLine("Modyfikatory dostępu");
Console.WriteLine("Klasy");
Console.WriteLine("Propertiesy i konstruktory");
Console.WriteLine("Klasy abstrakcyjne i interfejsy");
Console.WriteLine("Programowanie obiektowe");
Console.WriteLine("Paradygmaty programowania obiektowego (abstrakcja, enkapulsacja, dziedziczenia, polimorfizm)");
Console.WriteLine("LINQ");
Console.WriteLine("Tuples");
Console.WriteLine("Przeładowanie metod i operatorów");
Console.WriteLine("Extencion metody");
Console.WriteLine("Podstawy programowania asynchronicznego async await");
Console.WriteLine("Parametry funkcji out, ref");
Console.WriteLine("Testy jednostkowe");
Console.WriteLine("https://www.youtube.com/watch?v=nU2egLdGmzs&ab_channel=seesharpify");
Console.WriteLine("https://www.youtube.com/watch?v=mSpCRUEUMUU&ab_channel=kierunekdotNET");